/* tslint:disable */
/* eslint-disable */
/**
 * Leekwars API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type {AxiosResponse, AxiosInstance, AxiosRequestConfig} from "axios";
import globalAxios from "axios";
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * FunctionApi - axios parameter creator
 * @export
 */
export const FunctionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary function - get-all
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        functionGetAllGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/function/get-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary function - get-categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        functionGetCategoriesGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/function/get-categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FunctionApi - functional programming interface
 * @export
 */
export const FunctionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary function - get-all
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async functionGetAllGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await FunctionApiAxiosParamCreator(configuration).functionGetAllGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary function - get-categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async functionGetCategoriesGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await FunctionApiAxiosParamCreator(configuration).functionGetCategoriesGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * FunctionApi - factory interface
 * @export
 */
export const FunctionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary function - get-all
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async functionGetAllGet(options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return FunctionApiFp(configuration).functionGetAllGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary function - get-categories
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async functionGetCategoriesGet(options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return FunctionApiFp(configuration).functionGetCategoriesGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FunctionApi - object-oriented interface
 * @export
 * @class FunctionApi
 * @extends {BaseAPI}
 */
export class FunctionApi extends BaseAPI {
    /**
     * 
     * @summary function - get-all
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FunctionApi
     */
    public async functionGetAllGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return FunctionApiFp(this.configuration).functionGetAllGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary function - get-categories
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FunctionApi
     */
    public async functionGetCategoriesGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return FunctionApiFp(this.configuration).functionGetCategoriesGet(options).then((request) => request(this.axios, this.basePath));
    }
}
