/* tslint:disable */
/* eslint-disable */
/**
 * Leekwars API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import type {AxiosResponse, AxiosInstance, AxiosRequestConfig} from "axios";
import globalAxios from "axios";
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * PotionApi - axios parameter creator
 * @export
 */
export const PotionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary potion - get-all
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        potionGetAllGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/potion/get-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PotionApi - functional programming interface
 * @export
 */
export const PotionApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary potion - get-all
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async potionGetAllGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<any>>> {
            const localVarAxiosArgs = await PotionApiAxiosParamCreator(configuration).potionGetAllGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * PotionApi - factory interface
 * @export
 */
export const PotionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary potion - get-all
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async potionGetAllGet(options?: AxiosRequestConfig): Promise<AxiosResponse<any>> {
            return PotionApiFp(configuration).potionGetAllGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PotionApi - object-oriented interface
 * @export
 * @class PotionApi
 * @extends {BaseAPI}
 */
export class PotionApi extends BaseAPI {
    /**
     * 
     * @summary potion - get-all
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PotionApi
     */
    public async potionGetAllGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<any>> {
        return PotionApiFp(this.configuration).potionGetAllGet(options).then((request) => request(this.axios, this.basePath));
    }
}
