/* tslint:disable */
/* eslint-disable */
/**
 * Leekwars API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/ai-api';
export * from './apis/ai-folder-api';
export * from './apis/article-api';
export * from './apis/changelog-api';
export * from './apis/chip-api';
export * from './apis/complexity-api';
export * from './apis/constant-api';
export * from './apis/country-api';
export * from './apis/encyclopedia-api';
export * from './apis/farmer-api';
export * from './apis/fight-api';
export * from './apis/forum-api';
export * from './apis/function-api';
export * from './apis/garden-api';
export * from './apis/groupe-api';
export * from './apis/hat-api';
export * from './apis/history-api';
export * from './apis/item-api';
export * from './apis/lang-api';
export * from './apis/leek-api';
export * from './apis/leek-wars-api';
export * from './apis/market-api';
export * from './apis/message-api';
export * from './apis/message-reaction-api';
export * from './apis/notification-api';
export * from './apis/pomp-api';
export * from './apis/potion-api';
export * from './apis/ranking-api';
export * from './apis/service-api';
export * from './apis/summon-api';
export * from './apis/talent-api';
export * from './apis/team-api';
export * from './apis/team-composition-api';
export * from './apis/test-leek-api';
export * from './apis/test-map-api';
export * from './apis/test-scenario-api';
export * from './apis/tournament-api';
export * from './apis/trophy-api';
export * from './apis/trophy-template-api';
export * from './apis/weapon-api';

